#  - alias: Check sensor value and show notification
#    trigger:
#      platform: numeric_state
#      entity_id: sensor.random_sensor
#      above: 10
#    action:
#      service: notify.HOMEASSISTANT
#      data:
#        message: "Sensor value greater than 10"
#        title: "Custom subject"


    
  - alias: Reset SensoreRF state
    hide_entity: true
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.SensoreRF
      from: 'off'
      to: 'on'
      for:
        seconds: 5
    action:
    - service: mqtt.publish
      data:
        topic: tele/RF_Bridge/RESULT
        payload: 89B1B9off

  - alias: Reset SensoreRF2 state
    hide_entity: true
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.SensoreRF2
      from: 'off'
      to: 'on'
      for:
        seconds: 5
    action:
    - service: mqtt.publish
      data:
        topic: tele/RF_Bridge/RESULT
        payload: 8C4999off


  - alias: Reset sensoremovimento1 state
    hide_entity: true
    initial_state: 'on'
    trigger:
    - platform: state
      entity_id: binary_sensor.sensoremovimento1
      from: 'off'
      to: 'on'
      for:
        seconds: 5
    action:
    - service: mqtt.publish
      data:
        topic: tele/RF_Bridge/RESULT
        payload: 134046off