homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret rob_latitude
  longitude: !secret rob_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml

panel_iframe:
  configurator:
    title: Sonoff Bridge
    icon: mdi:wrench
    url: http://192.168.1.93  
  
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

http:
  #api_password: !secret rob_api_password
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: https://robig.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

ios:

shell_command:
  apri_cancello: curl -X GET http://192.168.1.79/APRI

homekit:

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.0/24

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_secret

# mysensors:
  # gateways:
    # - device: '/dev/ttyAMA0'

    
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_key    
    
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    pending_time: 0
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 30
      delay_time: 20
    
input_boolean:
  mute_gateway_sounds:
    name: Mute
    icon: mdi:volume-off
    
telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_rob_id
mqtt:
  password: !secret mqtt_password
  #utente: homeassistant
     
notify: !include notifies.yaml
sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include_dir_merge_list includes/automation/
script: !include scripts.yaml
switch: !include switches.yaml
binary_sensor: !include binarysensors.yaml

